spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abdou-karim/begging-spring-boot-micro-service-files-config
        default-label: master
server:
  port: 1111